"""
Generates branded financial statement PDFs with:
- AccurateA header with logo (text-based, no image needed)
- Company name & period
- Professional table formatting
- Watermark on every page
- Download metadata (date, time, user)
- Optional transaction drill-down
"""

import io
from datetime import datetime, date
from typing import Dict, Any, List, Optional
from decimal import Decimal

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import mm, cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph,
    Spacer, PageBreak, HRFlowable,
)
from reportlab.pdfgen import canvas


# Brand colours
BRAND_GREEN = colors.HexColor("#10B981")      # AccurateA green
BRAND_DARK = colors.HexColor("#0F172A")        # Dark header
BRAND_MUTED = colors.HexColor("#64748B")       # Muted text
BRAND_LIGHT_BG = colors.HexColor("#F8FAFC")    # Alternate row
BRAND_BORDER = colors.HexColor("#E2E8F0")      # Table borders
WHITE = colors.white


class BrandedPageTemplate:
    """Add AccurateA header, watermark, and footer to every page."""

    def __init__(
        self,
        company_name: str,
        report_title: str,
        period_text: str,
        downloaded_by: str,
    ):
        self.company_name = company_name
        self.report_title = report_title
        self.period_text = period_text
        self.downloaded_by = downloaded_by
        self.download_time = datetime.now()

    def on_page(self, canvas_obj: canvas.Canvas, doc):
        """Called on every page — draws header, watermark, footer."""
        width, height = doc.pagesize
        canvas_obj.saveState()

        # Watermark (diagonal, faint)
        canvas_obj.setFillColor(colors.HexColor("#E2E8F0"))
        canvas_obj.setFont("Helvetica-Bold", 60)
        canvas_obj.translate(width / 2, height / 2)
        canvas_obj.rotate(45)
        canvas_obj.drawCentredString(0, 0, "AccurateA")
        canvas_obj.rotate(-45)
        canvas_obj.translate(-width / 2, -height / 2)

        # Header bar
        canvas_obj.setFillColor(BRAND_DARK)
        canvas_obj.rect(0, height - 28 * mm, width, 28 * mm, fill=True, stroke=False)

        # Logo text: "☕ AccurateA"
        import os
        logo_path = os.path.join(
            os.path.dirname(os.path.dirname(__file__)),
            "assets", "AALogo.png"
        )
        if os.path.exists(logo_path):
            canvas_obj.drawImage(
                logo_path,
                10 * mm,  # x position
                height - 26 * mm,  # y position
                width=22 * mm,  # logo width
                height=22 * mm,  # logo height
                preserveAspectRatio=True,
                mask="auto",  # handles transparency
            )
            # Text next to logo
            canvas_obj.setFillColor(WHITE)
            canvas_obj.setFont("Helvetica-Bold", 14)
            canvas_obj.drawString(34 * mm, height - 15 * mm, "Accuratea")
            canvas_obj.setFillColor(colors.HexColor("#94A3B8"))
            canvas_obj.setFont("Helvetica", 7)
            canvas_obj.drawString(34 * mm, height - 20 * mm, "ACCURATE ACCOUNTING")
        else:
            # Fallback text if logo file not found
            canvas_obj.setFillColor(WHITE)
            canvas_obj.setFont("Helvetica-Bold", 16)
            canvas_obj.drawString(15 * mm, height - 15 * mm, "Accuratea")

        # Report title (right side of header)
        canvas_obj.setFillColor(colors.HexColor("#94A3B8"))
        canvas_obj.setFont("Helvetica", 9)
        canvas_obj.drawRightString(width - 15 * mm, height - 10 * mm, self.report_title)
        canvas_obj.drawRightString(width - 15 * mm, height - 15 * mm, self.period_text)

        # Company name (below header bar)
        canvas_obj.setFillColor(BRAND_DARK)
        canvas_obj.setFont("Helvetica-Bold", 11)
        canvas_obj.drawString(15 * mm, height - 38 * mm, self.company_name)

        # Footer
        canvas_obj.setFillColor(BRAND_BORDER)
        canvas_obj.line(15 * mm, 15 * mm, width - 15 * mm, 15 * mm)

        canvas_obj.setFillColor(BRAND_MUTED)
        canvas_obj.setFont("Helvetica", 7)

        footer_left = (
            f"Downloaded by {self.downloaded_by} on "
            f"{self.download_time.strftime('%d %b %Y at %H:%M')}"
        )
        canvas_obj.drawString(15 * mm, 10 * mm, footer_left)

        footer_right = f"Page {doc.page} — Generated by AccurateA"
        canvas_obj.drawRightString(width - 15 * mm, 10 * mm, footer_right)

        canvas_obj.restoreState()


class PDFExportService:
    """Generate branded PDF financial statements."""

    def __init__(self, company_name: str, downloaded_by: str):
        self.company_name = company_name
        self.downloaded_by = downloaded_by

    def _create_doc(
        self,
        report_title: str,
        period_text: str,
        landscape_mode: bool = False,
    ) -> tuple:
        """Create PDF document with branded template."""
        buffer = io.BytesIO()
        page_size = landscape(A4) if landscape_mode else A4

        doc = SimpleDocTemplate(
            buffer,
            pagesize=page_size,
            topMargin=45 * mm,
            bottomMargin=22 * mm,
            leftMargin=15 * mm,
            rightMargin=15 * mm,
        )

        template = BrandedPageTemplate(
            company_name=self.company_name,
            report_title=report_title,
            period_text=period_text,
            downloaded_by=self.downloaded_by,
        )

        return doc, buffer, template

    def _fmt(self, value: float, show_zero: bool = False) -> str:
        """Format currency for PDF."""
        if value == 0 and not show_zero:
            return ""
        return f"£{abs(value):,.2f}"

    def _make_table(
        self,
        headers: List[str],
        rows: List[List[str]],
        col_widths: Optional[List[float]] = None,
        totals_row: Optional[List[str]] = None,
    ) -> Table:
        """Create a professionally styled table."""
        data = [headers] + rows
        if totals_row:
            data.append(totals_row)

        table = Table(data, colWidths=col_widths, repeatRows=1)

        style_cmds = [
            # Header
            ("BACKGROUND", (0, 0), (-1, 0), BRAND_DARK),
            ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 8),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
            ("TOPPADDING", (0, 0), (-1, 0), 6),

            # Body
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 1), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
            ("TOPPADDING", (0, 1), (-1, -1), 4),
            ("GRID", (0, 0), (-1, -1), 0.5, BRAND_BORDER),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]

        # Alternate row colours
        for i in range(1, len(data)):
            if i % 2 == 0:
                style_cmds.append(
                    ("BACKGROUND", (0, i), (-1, i), BRAND_LIGHT_BG)
                )

        # Right-align numeric columns (all except first two)
        for col in range(2, len(headers)):
            style_cmds.append(("ALIGN", (col, 0), (col, -1), "RIGHT"))

        # Totals row styling
        if totals_row:
            last = len(data) - 1
            style_cmds.extend([
                ("BACKGROUND", (0, last), (-1, last), BRAND_DARK),
                ("TEXTCOLOR", (0, last), (-1, last), WHITE),
                ("FONTNAME", (0, last), (-1, last), "Helvetica-Bold"),
            ])

        table.setStyle(TableStyle(style_cmds))
        return table


    # INCOME STATEMENT PDF
    def generate_income_statement(
        self,
        data: Dict[str, Any],
        start_date: str,
        end_date: str,
        transactions: Optional[Dict[str, List]] = None,
    ) -> bytes:
        """Generate Income Statement PDF."""
        doc, buffer, template = self._create_doc(
            "Income Statement (P&L)",
            f"{start_date} to {end_date}",
        )

        elements = []

        # Revenue section
        elements.append(Paragraph(
            "<b>Revenue</b>",
            ParagraphStyle("SectionHead", fontSize=10, textColor=BRAND_GREEN,
                           spaceAfter=4, spaceBefore=8)
        ))

        rev_rows = []
        for acc in data.get("revenue", {}).get("accounts", []):
            rev_rows.append([acc["account_code"], acc["account_name"], "", self._fmt(acc["balance"])])

            # Transaction drill-down
            if transactions and acc["account_id"] in transactions:
                for txn in transactions[acc["account_id"]]:
                    rev_rows.append([
                        "", f"    {txn['date']} — {txn['description']}",
                        self._fmt(txn["debit"]), self._fmt(txn["credit"]),
                    ])

        rev_total = data.get("revenue", {}).get("total", 0)
        elements.append(self._make_table(
            ["Code", "Account", "Debit (£)", "Credit (£)"],
            rev_rows,
            col_widths=[50, 250, 80, 80],
            totals_row=["", "Total Revenue", "", self._fmt(rev_total)],
        ))

        elements.append(Spacer(1, 12))

        # Expenses section
        elements.append(Paragraph(
            "<b>Expenses</b>",
            ParagraphStyle("SectionHead", fontSize=10,
                           textColor=colors.HexColor("#EF4444"),
                           spaceAfter=4, spaceBefore=8)
        ))

        exp_rows = []
        for acc in data.get("expenses", {}).get("accounts", []):
            exp_rows.append([acc["account_code"], acc["account_name"], self._fmt(acc["balance"]), ""])

            if transactions and acc["account_id"] in transactions:
                for txn in transactions[acc["account_id"]]:
                    exp_rows.append([
                        "", f"    {txn['date']} — {txn['description']}",
                        self._fmt(txn["debit"]), self._fmt(txn["credit"]),
                    ])

        exp_total = data.get("expenses", {}).get("total", 0)
        elements.append(self._make_table(
            ["Code", "Account", "Debit (£)", "Credit (£)"],
            exp_rows,
            col_widths=[50, 250, 80, 80],
            totals_row=["", "Total Expenses", self._fmt(exp_total), ""],
        ))

        elements.append(Spacer(1, 16))

        # Net Income
        net = data.get("net_income", 0)
        label = "Net Profit" if net >= 0 else "Net Loss"
        net_color = BRAND_GREEN if net >= 0 else colors.HexColor("#EF4444")
        elements.append(Paragraph(
            f"<b>{label}: £{abs(net):,.2f}</b>",
            ParagraphStyle("NetIncome", fontSize=14, textColor=net_color,
                           alignment=TA_RIGHT, spaceBefore=8)
        ))

        doc.build(elements, onFirstPage=template.on_page, onLaterPages=template.on_page)
        return buffer.getvalue()


    # BALANCE SHEET PDF
    def generate_balance_sheet(
        self,
        data: Dict[str, Any],
        as_of_date: str,
        transactions: Optional[Dict[str, List]] = None,
    ) -> bytes:
        """Generate Balance Sheet PDF."""
        doc, buffer, template = self._create_doc(
            "Balance Sheet",
            f"As at {as_of_date}",
        )

        elements = []

        for section_key, section_label, section_color in [
            ("assets", "Assets", colors.HexColor("#3B82F6")),
            ("liabilities", "Liabilities", colors.HexColor("#F59E0B")),
            ("equity", "Equity", colors.HexColor("#8B5CF6")),
        ]:
            section = data.get(section_key, {})
            elements.append(Paragraph(
                f"<b>{section_label}</b>",
                ParagraphStyle("SH", fontSize=10, textColor=section_color,
                               spaceAfter=4, spaceBefore=10)
            ))

            rows = []
            for acc in section.get("accounts", []):
                rows.append([acc["account_code"], acc["account_name"], self._fmt(acc["balance"])])

                if transactions and acc["account_id"] in transactions:
                    for txn in transactions[acc["account_id"]]:
                        rows.append([
                            "", f"    {txn['date']} — {txn['description']}",
                            self._fmt(txn["debit"] - txn["credit"]),
                        ])

            elements.append(self._make_table(
                ["Code", "Account", "Amount (£)"],
                rows,
                col_widths=[50, 300, 100],
                totals_row=["", f"Total {section_label}", self._fmt(section.get("total", 0))],
            ))

            elements.append(Spacer(1, 6))

        doc.build(elements, onFirstPage=template.on_page, onLaterPages=template.on_page)
        return buffer.getvalue()


    # TRIAL BALANCE PDF
    def generate_trial_balance(
        self,
        data: Dict[str, Any],
        as_of_date: str,
        transactions: Optional[Dict[str, List]] = None,
    ) -> bytes:
        """Generate Trial Balance PDF."""
        doc, buffer, template = self._create_doc(
            "Trial Balance",
            f"As at {as_of_date}",
        )

        elements = []
        rows = []
        for acc in data.get("accounts", []):
            rows.append([
                acc["account_code"], acc["account_name"],
                self._fmt(acc["debit"]), self._fmt(acc["credit"]),
            ])

            if transactions and acc["account_id"] in transactions:
                for txn in transactions[acc["account_id"]]:
                    rows.append([
                        "", f"    {txn['date']} — {txn['description']}",
                        self._fmt(txn["debit"]), self._fmt(txn["credit"]),
                    ])

        elements.append(self._make_table(
            ["Code", "Account", "Debit (£)", "Credit (£)"],
            rows,
            col_widths=[50, 260, 90, 90],
            totals_row=[
                "", "TOTALS",
                self._fmt(data.get("total_debits", 0)),
                self._fmt(data.get("total_credits", 0)),
            ],
        ))

        # Balance check
        balanced = data.get("is_balanced", False)
        check_text = "Trial Balance is BALANCED" if balanced else "⚠️ Trial Balance is OUT OF BALANCE"
        elements.append(Spacer(1, 8))
        elements.append(Paragraph(
            f"<b>{check_text}</b>",
            ParagraphStyle("Check", fontSize=9,
                           textColor=BRAND_GREEN if balanced else colors.HexColor("#EF4444"),
                           alignment=TA_CENTER)
        ))

        doc.build(elements, onFirstPage=template.on_page, onLaterPages=template.on_page)
        return buffer.getvalue()


    # EXTENDED TRIAL BALANCE PDF (landscape)
    def generate_etb(
        self,
        data: Dict[str, Any],
        start_date: str,
        end_date: str,
    ) -> bytes:
        """Generate ETB PDF in landscape."""
        doc, buffer, template = self._create_doc(
            "Extended Trial Balance",
            f"{start_date} to {end_date}",
            landscape_mode=True,
        )

        elements = []
        rows = []
        for row in data.get("rows", []):
            rows.append([
                row["account_code"], row["account_name"],
                self._fmt(row["tb_dr"]), self._fmt(row["tb_cr"]),
                self._fmt(row["adj_dr"]), self._fmt(row["adj_cr"]),
                self._fmt(row["atb_dr"]), self._fmt(row["atb_cr"]),
                self._fmt(row["pl_dr"]), self._fmt(row["pl_cr"]),
                self._fmt(row["bs_dr"]), self._fmt(row["bs_cr"]),
            ])

        totals = data.get("totals", {})
        elements.append(self._make_table(
            ["Code", "Account", "TB Dr", "TB Cr", "Adj Dr", "Adj Cr",
             "ATB Dr", "ATB Cr", "P&L Dr", "P&L Cr", "BS Dr", "BS Cr"],
            rows,
            col_widths=[40, 130, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
            totals_row=[
                "", "TOTALS",
                self._fmt(totals.get("tb_dr", 0)), self._fmt(totals.get("tb_cr", 0)),
                self._fmt(totals.get("adj_dr", 0)), self._fmt(totals.get("adj_cr", 0)),
                self._fmt(totals.get("atb_dr", 0)), self._fmt(totals.get("atb_cr", 0)),
                self._fmt(totals.get("pl_dr", 0)), self._fmt(totals.get("pl_cr", 0)),
                self._fmt(totals.get("bs_dr", 0)), self._fmt(totals.get("bs_cr", 0)),
            ],
        ))

        doc.build(elements, onFirstPage=template.on_page, onLaterPages=template.on_page)
        return buffer.getvalue()
