"""Added accounts and transactions tables

Revision ID: 087c9c9cd2c1
Revises: 04cc3d4fdabe
Create Date: 2025-12-17 19:41:53.292273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087c9c9cd2c1'
down_revision: Union[str, None] = '04cc3d4fdabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('company_id', sa.UUID(), nullable=False, comment='Company this account belongs to'),
    sa.Column('account_name', sa.String(length=255), nullable=False, comment='Account name (e.g Cash, Revenue, Office Expenses)'),
    sa.Column('account_type', sa.String(length=50), nullable=False, comment='Type: asset, liability, equity, revenue, expense'),
    sa.Column('account_subtype', sa.String(length=50), nullable=True, comment='Subtype: current_asset, fixed_asset, operating_expenses etc'),
    sa.Column('parent_account_id', sa.UUID(), nullable=True, comment='Parent account for sub-accounts'),
    sa.Column('normal_balance', sa.String(length=10), nullable=True, comment='Normal balance: debit or credit'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is this account active?'),
    sa.Column('allow_many_entries', sa.Boolean(), nullable=False, comment='Allow manual journal entries to this account?'),
    sa.Column('tax_treatment', sa.String(length=50), nullable=True, comment='Tax treatment: deductible, non_deductible, capitalized'),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=False, comment='Current account balance'),
    sa.Column('description', sa.String(), nullable=True, comment='Account description'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_accounts_company_id'), 'accounts', ['company_id'], unique=False)
    op.create_table('transactions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='Source: bank, stripe, paypal, manual, scv_import'),
    sa.Column('source_id', sa.String(length=255), nullable=True, comment='External ID from source system'),
    sa.Column('transaction_date', sa.Date(), nullable=False, comment='Transaction date'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='Transaction amount'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Currency code (USD, EUR, GBP, etc)'),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True, comment='Vendor or Customer name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Transaction description'),
    sa.Column('memo', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Transaction category assigned by the AI'),
    sa.Column('gl_account_id', sa.UUID(), nullable=True, comment='General ledger account assigned by AI'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='Department or cost center'),
    sa.Column('classification_status', sa.String(length=20), nullable=False, comment='Status: pending, auto_approved, needs_review, approved'),
    sa.Column('classification_confidence', sa.Numeric(precision=5, scale=4), nullable=True, comment='AI confidence score (0 to 1'),
    sa.Column('classified_by', sa.String(length=20), nullable=True, comment='Who classified: ai, user, rule'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: pending, processed, void'),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False, comment='Has user reviewed this?'),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gl_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_transactions_company_id'), 'transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_company_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_accounts_company_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
