"""Added anomalies table

Revision ID: 0ce8452fa464
Revises: f995e0109395
Create Date: 2025-12-30 10:35:53.849976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce8452fa464'
down_revision: Union[str, None] = 'f995e0109395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True, comment='Transaction that triggered anomaly (if applicable)'),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False, comment='Type: duplicate, unusual_amount, frequency, new_vendor, etc.'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='Severity: low, medium, high, critical'),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False, comment='Risk score (0-100)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short description'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed explanation'),
    sa.Column('detected_at', sa.Date(), nullable=False, comment='When detected'),
    sa.Column('detected_by', sa.String(length=20), nullable=False, comment='Detected by: ai, user, system'),
    sa.Column('detection_method', sa.String(length=50), nullable=True, comment='Method: statistical, pattern, rule_based'),
    sa.Column('evidence', sa.JSON(), nullable=True, comment='Supporting data (transactions, statistics, etc.)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: pending, reviewed, resolved, false_positive'),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.Date(), nullable=True, comment='When reviewed'),
    sa.Column('resolution_notes', sa.Text(), nullable=True, comment='How it was resolved'),
    sa.Column('is_false_positive', sa.Boolean(), nullable=False, comment='Was this a false alarm?'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_anomaly_company_status', 'anomalies', ['company_id', 'status'], unique=False)
    op.create_index('idx_anomaly_severity', 'anomalies', ['severity'], unique=False)
    op.create_index('idx_anomaly_type', 'anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomalies_anomaly_type'), 'anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomalies_company_id'), 'anomalies', ['company_id'], unique=False)
    op.create_index(op.f('ix_anomalies_detected_at'), 'anomalies', ['detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_severity'), 'anomalies', ['severity'], unique=False)
    op.create_index(op.f('ix_anomalies_status'), 'anomalies', ['status'], unique=False)
    op.create_unique_constraint(None, 'tax_categories', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tax_categories', type_='unique')
    op.drop_index(op.f('ix_anomalies_status'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_severity'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_detected_at'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_company_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_type'), table_name='anomalies')
    op.drop_index('idx_anomaly_type', table_name='anomalies')
    op.drop_index('idx_anomaly_severity', table_name='anomalies')
    op.drop_index('idx_anomaly_company_status', table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
