"""Added open_banking_connections table and company country

Revision ID: 1568d5454dac
Revises: c7e461de3b95
Create Date: 2026-03-03 08:34:11.912414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1568d5454dac'
down_revision: Union[str, None] = 'c7e461de3b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_banking_connections',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='Provider: truelayer, yapily'),
    sa.Column('access_token', sa.String(length=500), nullable=False, comment='OAuth access token'),
    sa.Column('refresh_token', sa.String(length=500), nullable=True, comment='OAuth refresh token'),
    sa.Column('token_expiry', sa.DateTime(), nullable=True, comment='When the access token expires'),
    sa.Column('consent_id', sa.String(length=255), nullable=True, comment='TrueLayer consent/connection ID'),
    sa.Column('institution_id', sa.String(length=255), nullable=False, comment='Bank institution ID'),
    sa.Column('institution_name', sa.String(length=255), nullable=False, comment='Bank name (e.g. Barclays, HSBC)'),
    sa.Column('account_ids', sa.JSON(), nullable=True, comment='List of connected account IDs'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.String(length=50), nullable=True, comment='Last successful sync timestamp'),
    sa.Column('error', sa.String(), nullable=True, comment='Last error message'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_ob_active', 'open_banking_connections', ['is_active'], unique=False)
    op.create_index('idx_ob_company', 'open_banking_connections', ['company_id'], unique=False)
    op.create_index(op.f('ix_open_banking_connections_company_id'), 'open_banking_connections', ['company_id'], unique=False)
    op.create_index(op.f('ix_open_banking_connections_user_id'), 'open_banking_connections', ['user_id'], unique=False)
    op.add_column('companies', sa.Column('country', sa.String(length=2), nullable=False, server_default='GB', comment='ISO country code (GB, US, etc.)'))
    op.create_unique_constraint(None, 'fiscal_periods', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fiscal_periods', type_='unique')
    op.drop_column('companies', 'country')
    op.drop_index(op.f('ix_open_banking_connections_user_id'), table_name='open_banking_connections')
    op.drop_index(op.f('ix_open_banking_connections_company_id'), table_name='open_banking_connections')
    op.drop_index('idx_ob_company', table_name='open_banking_connections')
    op.drop_index('idx_ob_active', table_name='open_banking_connections')
    op.drop_table('open_banking_connections')
    # ### end Alembic commands ###
