"""Added account_code to the accounts table omitted initially

Revision ID: 41dcb5b3b900
Revises: 087c9c9cd2c1
Create Date: 2025-12-17 19:59:41.505299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41dcb5b3b900'
down_revision: Union[str, None] = '087c9c9cd2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_code', sa.String(length=20), nullable=False, comment='Account code (e.g., 1000, 4000, 6100)'))
    op.create_index(op.f('ix_accounts_account_code'), 'accounts', ['account_code'], unique=False)
    op.create_unique_constraint(None, 'accounts', ['id'])
    op.create_unique_constraint(None, 'transactions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_index(op.f('ix_accounts_account_code'), table_name='accounts')
    op.drop_column('accounts', 'account_code')
    # ### end Alembic commands ###
