"""Add email connections table (fixed circular FK)

Revision ID: 576862183c03
Revises: 773080ed9d0a
Create Date: 2026-01-08 10:09:29.880946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576862183c03'
down_revision: Union[str, None] = '773080ed9d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_journal_entry_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'journal_entry_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('journal_entry_id', sa.UUID(), autoincrement=False, nullable=True, comment='Linked journal entry (if posted)'))
    op.create_foreign_key('transactions_journal_entry_id_fkey', 'transactions', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
