"""added audit_logs table

Revision ID: 617d341cf3b3
Revises: 43fd0da0394a
Create Date: 2026-02-26 20:34:35.376029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '617d341cf3b3'
down_revision: Union[str, None] = '43fd0da0394a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User who performed the action (NULL for system actions)'),
    sa.Column('company_id', sa.UUID(), nullable=False, comment='Company this action belongs to'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Action type: create, update, delete, post, void, approve, reject, login, export'),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='Entity type: journal_entry, transaction, account, vat_return, user, etc.'),
    sa.Column('entity_id', sa.String(length=36), nullable=True, comment='ID of the affected entity (NULL for bulk actions)'),
    sa.Column('description', sa.Text(), nullable=False, comment='Human-readable description of what happened'),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="JSON object with 'before' and 'after' snapshots of changed fields"),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address (supports IPv6)'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='Client user agent string'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='When the action occurred'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_audit_company_timestamp', 'audit_logs', ['company_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_user_timestamp', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_unique_constraint(None, 'refresh_tokens', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_index('ix_audit_user_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_company_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
