"""Add email connections table

Revision ID: 6b462285a1ba
Revises: 576862183c03
Create Date: 2026-01-08 23:19:08.626739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b462285a1ba'
down_revision: Union[str, None] = '576862183c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_connections',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False, comment='gmail_oauth, dedicated_inbox, manual'),
    sa.Column('gmail_email', sa.String(length=255), nullable=True, comment='Connected Gmail address'),
    sa.Column('gmail_tokens', sa.JSON(), nullable=True, comment='OAuth tokens (encrypted in production)'),
    sa.Column('forwarding_email', sa.String(length=255), nullable=True, comment='Unique forwarding email for this company'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_check_at', sa.String(length=50), nullable=True, comment='Last email check timestamp'),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('emails_processed', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forwarding_email'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_email_connection_active', 'email_connections', ['is_active'], unique=False)
    op.create_index('idx_email_connection_company', 'email_connections', ['company_id'], unique=False)
    op.create_index(op.f('ix_email_connections_company_id'), 'email_connections', ['company_id'], unique=False)
    op.create_index(op.f('ix_email_connections_user_id'), 'email_connections', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_connections_user_id'), table_name='email_connections')
    op.drop_index(op.f('ix_email_connections_company_id'), table_name='email_connections')
    op.drop_index('idx_email_connection_company', table_name='email_connections')
    op.drop_index('idx_email_connection_active', table_name='email_connections')
    op.drop_table('email_connections')
    # ### end Alembic commands ###
