"""Add journal_entry_id to transactions table

Revision ID: 773080ed9d0a
Revises: ca0ed4bb5269
Create Date: 2026-01-08 08:13:47.623328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '773080ed9d0a'
down_revision: Union[str, None] = 'ca0ed4bb5269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plaid_items', 'account_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_comment='List of Plaid account IDs')
    op.create_unique_constraint(None, 'plaid_items', ['id'])
    op.add_column('transactions', sa.Column('journal_entry_id', sa.UUID(), nullable=True, comment='Linked journal entry (if posted)'))
    op.create_foreign_key(None, 'transactions', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'journal_entry_id')
    op.drop_constraint(None, 'plaid_items', type_='unique')
    op.alter_column('plaid_items', 'account_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_comment='List of Plaid account IDs')
    # ### end Alembic commands ###
