"""added bank_rules table

Revision ID: 77ab8caddb18
Revises: 1568d5454dac
Create Date: 2026-03-03 08:55:01.483346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ab8caddb18'
down_revision: Union[str, None] = '1568d5454dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_rules',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Rule name e.g. 'AWS charges → Cloud Hosting'"),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Priority 1-100 (lower = higher priority)'),
    sa.Column('condition_field', sa.String(length=50), nullable=False, comment='Field to match: description, merchant_name, amount, category'),
    sa.Column('condition_operator', sa.String(length=50), nullable=False, comment='Operator: contains, equals, starts_with, ends_with, greater_than, less_than'),
    sa.Column('condition_value', sa.String(length=500), nullable=False, comment='Value to match against'),
    sa.Column('action_category', sa.String(length=255), nullable=True, comment='Category to assign if matched'),
    sa.Column('action_account_id', sa.UUID(), nullable=True, comment='GL account to assign if matched'),
    sa.Column('action_vat_rate_id', sa.UUID(), nullable=True, comment='VAT rate to assign if matched'),
    sa.Column('action_description', sa.String(length=500), nullable=True, comment='Override description (optional)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['action_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_bank_rule_company', 'bank_rules', ['company_id'], unique=False)
    op.create_index('idx_bank_rule_priority', 'bank_rules', ['priority'], unique=False)
    op.create_index(op.f('ix_bank_rules_company_id'), 'bank_rules', ['company_id'], unique=False)
    op.create_unique_constraint(None, 'open_banking_connections', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'open_banking_connections', type_='unique')
    op.drop_index(op.f('ix_bank_rules_company_id'), table_name='bank_rules')
    op.drop_index('idx_bank_rule_priority', table_name='bank_rules')
    op.drop_index('idx_bank_rule_company', table_name='bank_rules')
    op.drop_table('bank_rules')
    # ### end Alembic commands ###
