"""Added journal entries system

Revision ID: 83d4c787cc5d
Revises: ae2062d6c084
Create Date: 2025-12-25 10:27:59.913779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d4c787cc5d'
down_revision: Union[str, None] = 'ae2062d6c084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True, comment='Source transaction (if any)'),
    sa.Column('entry_date', sa.Date(), nullable=False, comment='Journal entry date'),
    sa.Column('entry_number', sa.String(length=50), nullable=False, comment='Sequential entry number e.g JE-2025-001'),
    sa.Column('description', sa.Text(), nullable=False, comment='Entry description'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Source: ai, manual, import, system'),
    sa.Column('reference', sa.String(length=255), nullable=True, comment='External reference (invoice #, etc.)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: draft, posted, voided'),
    sa.Column('posted_at', sa.Date(), nullable=True, comment='When entry was posted'),
    sa.Column('posted_by_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_je_company_date', 'journal_entries', ['company_id', 'entry_date'], unique=False)
    op.create_index('idx_je_status', 'journal_entries', ['status'], unique=False)
    op.create_index(op.f('ix_journal_entries_company_id'), 'journal_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_table('journal_entry_lines',
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=2), nullable=False, comment='Debit amount'),
    sa.Column('credit', sa.Numeric(precision=15, scale=2), nullable=False, comment='Credit amount'),
    sa.Column('description', sa.Text(), nullable=True, comment='Line description'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_lines_account_id'), 'journal_entry_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_lines_journal_entry_id'), 'journal_entry_lines', ['journal_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entry_lines_journal_entry_id'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_journal_entry_lines_account_id'), table_name='journal_entry_lines')
    op.drop_table('journal_entry_lines')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_company_id'), table_name='journal_entries')
    op.drop_index('idx_je_status', table_name='journal_entries')
    op.drop_index('idx_je_company_date', table_name='journal_entries')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
