"""Added bank transactions and reconciliations

Revision ID: 89e51ed9c9d6
Revises: 98c794a19a0e
Create Date: 2025-12-26 08:41:04.043502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e51ed9c9d6'
down_revision: Union[str, None] = '98c794a19a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transactions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=True, comment='Which bank account (GL account)'),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment="Bank's transaction ID"),
    sa.Column('source', sa.String(length=50), nullable=False, comment='Source: plaid, csv, manual'),
    sa.Column('transaction_date', sa.Date(), nullable=False, comment='Transaction date from bank'),
    sa.Column('posted_date', sa.Date(), nullable=True, comment='When it posted (may differ from transaction date)'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='Amount (positive = deposit, negative = withdrawal)'),
    sa.Column('description', sa.Text(), nullable=False, comment="Bank's description"),
    sa.Column('merchant_name', sa.String(length=255), nullable=True, comment='Merchant name (from Plaid)'),
    sa.Column('category', sa.String(length=255), nullable=True, comment="Bank's category"),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False, comment='Has this been matched to a transaction?'),
    sa.Column('reconciled_at', sa.Date(), nullable=True, comment='When it was reconciled'),
    sa.Column('raw_data', sa.Text(), nullable=True, comment='Raw JSON from source'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_bank_txn_company_date', 'bank_transactions', ['company_id', 'transaction_date'], unique=False)
    op.create_index('idx_bank_txn_reconciled', 'bank_transactions', ['is_reconciled'], unique=False)
    op.create_index(op.f('ix_bank_transactions_company_id'), 'bank_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_is_reconciled'), 'bank_transactions', ['is_reconciled'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_date'), 'bank_transactions', ['transaction_date'], unique=False)
    op.create_table('reconciliations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('bank_transaction_id', sa.UUID(), nullable=False, comment='Bank transaction (external)'),
    sa.Column('transaction_id', sa.UUID(), nullable=False, comment='Our internal transaction'),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=4), nullable=True, comment='AI confidence in this match (0-1)'),
    sa.Column('match_method', sa.String(length=50), nullable=False, comment='Method: exact, fuzzy, ai, manual'),
    sa.Column('matched_by', sa.String(length=20), nullable=False, comment='Who made the match: ai, user'),
    sa.Column('matched_by_id', sa.UUID(), nullable=True),
    sa.Column('reconciled_date', sa.Date(), nullable=False, comment='When reconciliation was made'),
    sa.Column('amount_difference', sa.Numeric(precision=15, scale=2), nullable=False, comment='Difference in amounts (should be 0)'),
    sa.Column('date_difference_days', sa.Numeric(precision=5, scale=0), nullable=False, comment='Days difference in dates'),
    sa.Column('notes', sa.String(), nullable=True, comment='Notes about this reconciliation'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_transaction_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_recon_company_date', 'reconciliations', ['company_id', 'reconciled_date'], unique=False)
    op.create_index(op.f('ix_reconciliations_company_id'), 'reconciliations', ['company_id'], unique=False)
    op.create_unique_constraint(None, 'financial_statements', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'financial_statements', type_='unique')
    op.drop_index(op.f('ix_reconciliations_company_id'), table_name='reconciliations')
    op.drop_index('idx_recon_company_date', table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index(op.f('ix_bank_transactions_transaction_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_is_reconciled'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_company_id'), table_name='bank_transactions')
    op.drop_index('idx_bank_txn_reconciled', table_name='bank_transactions')
    op.drop_index('idx_bank_txn_company_date', table_name='bank_transactions')
    op.drop_table('bank_transactions')
    # ### end Alembic commands ###
