"""added assets table for depreciation

Revision ID: 959125f3f180
Revises: 6b462285a1ba
Create Date: 2026-01-10 10:15:41.930213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959125f3f180'
down_revision: Union[str, None] = '6b462285a1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment="Asset name (e.g., 'Company Vehicle 2024')"),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Detailed description'),
    sa.Column('asset_type', sa.String(length=50), nullable=False, comment='Type: equipment, vehicle, building, furniture, computer'),
    sa.Column('purchase_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='Original purchase price'),
    sa.Column('purchase_date', sa.Date(), nullable=False, comment='Date asset was purchased'),
    sa.Column('salvage_value', sa.Numeric(precision=15, scale=2), nullable=True, comment='Expected value at end of useful life'),
    sa.Column('is_depreciable', sa.Boolean(), nullable=True, comment='Whether asset should be depreciated'),
    sa.Column('depreciation_method', sa.String(length=50), nullable=True, comment='Method: straight_line, declining_balance'),
    sa.Column('useful_life_months', sa.Integer(), nullable=True, comment='Useful life in months (default: 60 = 5 years)'),
    sa.Column('depreciation_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Rate for declining balance (e.g., 2.0 for double-declining)'),
    sa.Column('asset_tag', sa.String(length=50), nullable=True, comment='Unique asset tag/serial number'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='Physical location of asset'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Status: active, disposed, sold'),
    sa.Column('disposal_date', sa.Date(), nullable=True, comment='Date asset was disposed/sold'),
    sa.Column('disposal_value', sa.Numeric(precision=15, scale=2), nullable=True, comment='Amount received on disposal'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_tag'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_asset_company_status', 'assets', ['company_id', 'status'], unique=False)
    op.create_index('idx_asset_type', 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_company_id'), 'assets', ['company_id'], unique=False)
    op.create_index(op.f('ix_assets_purchase_date'), 'assets', ['purchase_date'], unique=False)
    op.create_unique_constraint(None, 'email_connections', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_connections', type_='unique')
    op.drop_index(op.f('ix_assets_purchase_date'), table_name='assets')
    op.drop_index(op.f('ix_assets_company_id'), table_name='assets')
    op.drop_index('idx_asset_type', table_name='assets')
    op.drop_index('idx_asset_company_status', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
