"""Added financial statements table

Revision ID: 98c794a19a0e
Revises: 83d4c787cc5d
Create Date: 2025-12-25 18:00:56.952157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c794a19a0e'
down_revision: Union[str, None] = '83d4c787cc5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_statements',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('statement_type', sa.String(length=50), nullable=False, comment='Type: income_statement, balance_sheet, cash_flow'),
    sa.Column('period_start', sa.Date(), nullable=False, comment='Period start date'),
    sa.Column('period_end', sa.Date(), nullable=False, comment='Period end date (as of date)'),
    sa.Column('data', sa.JSON(), nullable=False, comment='Statement data (line items, totals, etc.)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: draft, final, published'),
    sa.Column('generated_by', sa.String(length=20), nullable=False, comment='Generated by: ai, user, system'),
    sa.Column('generated_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True, comment='Notes about this statement'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_fs_company_type_date', 'financial_statements', ['company_id', 'statement_type', 'period_end'], unique=False)
    op.create_index(op.f('ix_financial_statements_company_id'), 'financial_statements', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_statements_period_end'), 'financial_statements', ['period_end'], unique=False)
    op.create_unique_constraint(None, 'journal_entries', ['id'])
    op.create_unique_constraint(None, 'journal_entry_lines', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal_entry_lines', type_='unique')
    op.drop_constraint(None, 'journal_entries', type_='unique')
    op.drop_index(op.f('ix_financial_statements_period_end'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_company_id'), table_name='financial_statements')
    op.drop_index('idx_fs_company_type_date', table_name='financial_statements')
    op.drop_table('financial_statements')
    # ### end Alembic commands ###
