"""Added journal entries and lines tables

Revision ID: ae2062d6c084
Revises: 41dcb5b3b900
Create Date: 2025-12-25 09:12:19.402302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2062d6c084'
down_revision: Union[str, None] = '41dcb5b3b900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
