"""Rename irs_notes to tax_notes in tax_categories

Revision ID: c0dcea448d22
Revises: a89bfa63f646
Create Date: 2026-02-26 15:45:59.740284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0dcea448d22'
down_revision: Union[str, None] = 'a89bfa63f646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'assets', ['id'])
    op.add_column('tax_categories', sa.Column('tax_notes', sa.Text(), nullable=True, comment='Tax guidelines for this category'))
    op.drop_column('tax_categories', 'irs_notes')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether user account is active',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether user account is active',
               existing_nullable=False)
    op.add_column('tax_categories', sa.Column('irs_notes', sa.TEXT(), autoincrement=False, nullable=True, comment='IRS guidelines for this category'))
    op.drop_column('tax_categories', 'tax_notes')
    op.drop_constraint(None, 'assets', type_='unique')
    # ### end Alembic commands ###
