"""Added documents table for uploading of docs

Revision ID: c7e096bd0b82
Revises: d144fbba3988
Create Date: 2026-03-02 10:53:11.000437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7e096bd0b82'
down_revision: Union[str, None] = 'd144fbba3988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Original file name'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='MIME type: application/pdf, image/jpeg, image/png'),
    sa.Column('file_url', sa.String(length=1024), nullable=False, comment='Storage URL or signed URL for download'),
    sa.Column('storage_key', sa.String(length=512), nullable=False, comment='Storage path/key (e.g., S3 key or local path)'),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('document_type', sa.String(length=50), nullable=True, comment='Type: invoice, receipt, credit_note, bank_statement, expense_claim, other'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Status: uploaded, processing, processed, failed'),
    sa.Column('ocr_text', sa.Text(), nullable=True, comment='Raw text extracted via OCR'),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured data extracted by AI (amounts, dates, vendor, etc.)'),
    sa.Column('processing_error', sa.String(length=500), nullable=True, comment='Error message if processing failed'),
    sa.Column('linked_transaction_id', sa.UUID(), nullable=True, comment='Linked transaction (e.g., receipt matched to expense)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_doc_company_status', 'documents', ['company_id', 'status'], unique=False)
    op.create_index('idx_doc_company_type', 'documents', ['company_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_unique_constraint(None, 'vat_rates', ['id'])
    op.create_unique_constraint(None, 'vat_returns', ['id'])
    op.create_unique_constraint(None, 'vat_schemes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vat_schemes', type_='unique')
    op.drop_constraint(None, 'vat_returns', type_='unique')
    op.drop_constraint(None, 'vat_rates', type_='unique')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_index('idx_doc_company_type', table_name='documents')
    op.drop_index('idx_doc_company_status', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
