"""Added fiscal_periods table

Revision ID: c7e461de3b95
Revises: c7e096bd0b82
Create Date: 2026-03-03 07:22:30.375348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e461de3b95'
down_revision: Union[str, None] = 'c7e096bd0b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscal_periods',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="e.g. 'January 2025', 'Q1 2025', 'FY 2024-25'"),
    sa.Column('period_start', sa.Date(), nullable=False, comment='Start date of the period'),
    sa.Column('period_end', sa.Date(), nullable=False, comment='End date of the period'),
    sa.Column('period_type', sa.String(length=20), nullable=False, comment='month, quarter, year'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='open, closed, locked'),
    sa.Column('closed_by_id', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.Date(), nullable=True, comment='When the period was closed'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notes about the period close'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_fiscal_periods_company_id'), 'fiscal_periods', ['company_id'], unique=False)
    op.create_unique_constraint(None, 'documents', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_index(op.f('ix_fiscal_periods_company_id'), table_name='fiscal_periods')
    op.drop_table('fiscal_periods')
    # ### end Alembic commands ###
