"""Added Plaid items table

Revision ID: ca0ed4bb5269
Revises: 0ce8452fa464
Create Date: 2026-01-01 11:19:15.658127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0ed4bb5269'
down_revision: Union[str, None] = '0ce8452fa464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_items',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False, comment='Plaid Item ID'),
    sa.Column('access_token', sa.String(length=255), nullable=False, comment='Plaid access token (encrypted in production)'),
    sa.Column('institution_id', sa.String(length=255), nullable=False, comment='Plaid institution ID'),
    sa.Column('institution_name', sa.String(length=255), nullable=False, comment='Bank name'),
    sa.Column('account_ids', sa.JSON(), nullable=False, comment='List of Plaid account IDs'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is connection active?'),
    sa.Column('last_sync_at', sa.String(length=50), nullable=True, comment='Last successful sync timestamp'),
    sa.Column('error', sa.String(), nullable=True, comment='Last error message'),
    sa.Column('webhook_url', sa.String(length=500), nullable=True, comment='Webhook URL for updates'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_plaid_item_active', 'plaid_items', ['is_active'], unique=False)
    op.create_index('idx_plaid_item_company', 'plaid_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_plaid_items_company_id'), 'plaid_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_plaid_items_item_id'), 'plaid_items', ['item_id'], unique=True)
    op.create_index(op.f('ix_plaid_items_user_id'), 'plaid_items', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'anomalies', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anomalies', type_='unique')
    op.drop_index(op.f('ix_plaid_items_user_id'), table_name='plaid_items')
    op.drop_index(op.f('ix_plaid_items_item_id'), table_name='plaid_items')
    op.drop_index(op.f('ix_plaid_items_company_id'), table_name='plaid_items')
    op.drop_index('idx_plaid_item_company', table_name='plaid_items')
    op.drop_index('idx_plaid_item_active', table_name='plaid_items')
    op.drop_table('plaid_items')
    # ### end Alembic commands ###
