"""Added VAT models and transaction VAT fields

Revision ID: d144fbba3988
Revises: 617d341cf3b3
Create Date: 2026-02-27 11:57:12.007362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd144fbba3988'
down_revision: Union[str, None] = '617d341cf3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vat_rates',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Rate name: Standard, Reduced, Zero, Exempt, Outside Scope'),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='VAT percentage (e.g., 20.00, 5.00, 0.00). NULL for Exempt/Outside Scope.'),
    sa.Column('description', sa.Text(), nullable=True, comment='What this rate applies to'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='When this rate became effective'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='When this rate expired (NULL = still active)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is this rate currently in use?'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_vat_rate_active', 'vat_rates', ['is_active'], unique=False)
    op.create_index('idx_vat_rate_name', 'vat_rates', ['name'], unique=False)
    op.create_table('vat_schemes',
    sa.Column('company_id', sa.UUID(), nullable=False, comment='Company this scheme belongs to'),
    sa.Column('scheme_type', sa.String(length=20), nullable=False, comment='Scheme: standard, flat_rate, cash'),
    sa.Column('flat_rate_percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Flat rate % if on Flat Rate Scheme (varies by industry, e.g., 14.5% for IT)'),
    sa.Column('vat_registration_number', sa.String(length=20), nullable=True, comment='VAT registration number (e.g., GB 123 4567 89)'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='When the company registered for this scheme'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='When the company left this scheme (NULL = still active)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_vat_scheme_company', 'vat_schemes', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_vat_schemes_company_id'), 'vat_schemes', ['company_id'], unique=False)
    op.create_table('vat_returns',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False, comment='Start of VAT period (e.g., 2025-01-01)'),
    sa.Column('period_end', sa.Date(), nullable=False, comment='End of VAT period (e.g., 2025-03-31)'),
    sa.Column('box1_vat_due_sales', sa.Numeric(precision=15, scale=2), nullable=False, comment='Box 1: VAT due on sales and other outputs'),
    sa.Column('box2_vat_due_acquisitions', sa.Numeric(precision=15, scale=2), nullable=False, comment='Box 2: VAT due on acquisitions from EU member states'),
    sa.Column('box3_total_vat_due', sa.Numeric(precision=15, scale=2), nullable=False, comment='Box 3: Total VAT due (Box 1 + Box 2)'),
    sa.Column('box4_vat_reclaimed', sa.Numeric(precision=15, scale=2), nullable=False, comment='Box 4: VAT reclaimed on purchases and other inputs'),
    sa.Column('box5_net_vat', sa.Numeric(precision=15, scale=2), nullable=False, comment='Box 5: Net VAT to pay or reclaim (Box 3 - Box 4). Positive = pay, negative = reclaim.'),
    sa.Column('box6_total_sales_excl_vat', sa.Numeric(precision=15, scale=2), nullable=False, comment='Box 6: Total value of sales excl. VAT (whole pounds)'),
    sa.Column('box7_total_purchases_excl_vat', sa.Numeric(precision=15, scale=2), nullable=False, comment='Box 7: Total value of purchases excl. VAT (whole pounds)'),
    sa.Column('box8_total_supplies_eu', sa.Numeric(precision=15, scale=2), nullable=False, comment='Box 8: Total value of supplies of goods to EU (post-Brexit: usually 0)'),
    sa.Column('box9_total_acquisitions_eu', sa.Numeric(precision=15, scale=2), nullable=False, comment='Box 9: Total value of acquisitions from EU (post-Brexit: usually 0)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: draft, submitted, accepted, rejected'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes about this return'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='When this return was submitted to HMRC'),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True, comment='Who submitted this return'),
    sa.Column('hmrc_receipt_id', sa.String(length=255), nullable=True, comment='HMRC receipt/confirmation ID after successful submission'),
    sa.Column('hmrc_processing_date', sa.DateTime(), nullable=True, comment='When HMRC processed this return'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_vat_return_company_period', 'vat_returns', ['company_id', 'period_start', 'period_end'], unique=False)
    op.create_index('idx_vat_return_status', 'vat_returns', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_vat_returns_company_id'), 'vat_returns', ['company_id'], unique=False)
    op.create_unique_constraint(None, 'audit_logs', ['id'])
    op.add_column('transactions', sa.Column('vat_rate_id', sa.UUID(), nullable=True, comment='Which VAT rate applies (Standard 20%, Reduced 5%, Zero, Exempt, etc.)'))
    op.add_column('transactions', sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='VAT amount in currency (e.g., 30.00 on a £150 + VAT purchase)'))
    op.add_column('transactions', sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Amount excluding VAT (e.g., 150.00)'))
    op.add_column('transactions', sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Amount including VAT (e.g., 180.00)'))
    op.add_column('transactions', sa.Column('vat_type', sa.String(length=10), nullable=True, comment="'input' (purchases — reclaimable) or 'output' (sales — payable to HMRC)"))
    op.add_column('transactions', sa.Column('vat_inclusive', sa.Boolean(), nullable=True, comment='Was the original transaction amount VAT-inclusive? True = gross, False = net'))
    op.create_foreign_key(None, 'transactions', 'vat_rates', ['vat_rate_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='Role: owner, admin, accountant, bookkeeper, viewer',
               existing_comment='Role: owner, admin, accountant, member, viewer',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='Role: owner, admin, accountant, member, viewer',
               existing_comment='Role: owner, admin, accountant, bookkeeper, viewer',
               existing_nullable=False)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'vat_inclusive')
    op.drop_column('transactions', 'vat_type')
    op.drop_column('transactions', 'gross_amount')
    op.drop_column('transactions', 'net_amount')
    op.drop_column('transactions', 'vat_amount')
    op.drop_column('transactions', 'vat_rate_id')
    op.drop_constraint(None, 'audit_logs', type_='unique')
    op.drop_index(op.f('ix_vat_returns_company_id'), table_name='vat_returns')
    op.drop_index('idx_vat_return_status', table_name='vat_returns')
    op.drop_index('idx_vat_return_company_period', table_name='vat_returns')
    op.drop_table('vat_returns')
    op.drop_index(op.f('ix_vat_schemes_company_id'), table_name='vat_schemes')
    op.drop_index('idx_vat_scheme_company', table_name='vat_schemes')
    op.drop_table('vat_schemes')
    op.drop_index('idx_vat_rate_name', table_name='vat_rates')
    op.drop_index('idx_vat_rate_active', table_name='vat_rates')
    op.drop_table('vat_rates')
    # ### end Alembic commands ###
