"""Added tax categories and tax fields to transactions

Revision ID: f995e0109395
Revises: 89e51ed9c9d6
Create Date: 2025-12-30 07:27:14.632061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f995e0109395'
down_revision: Union[str, None] = '89e51ed9c9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_categories',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Tax category name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of this category'),
    sa.Column('is_deductible', sa.Boolean(), nullable=False, comment='Is this expense tax deductible?'),
    sa.Column('deduction_percentage', sa.Numeric(precision=5, scale=2), nullable=False, comment='Percentage deductible (0-100)'),
    sa.Column('tax_form', sa.String(length=50), nullable=True, comment='IRS form (Schedule C, etc.)'),
    sa.Column('tax_line', sa.String(length=50), nullable=True, comment='Line number on tax form'),
    sa.Column('requires_receipt', sa.Boolean(), nullable=False, comment='Must have receipt?'),
    sa.Column('requires_documentation', sa.Boolean(), nullable=False, comment='Requires additional documentation?'),
    sa.Column('max_amount_without_receipt', sa.Numeric(precision=15, scale=2), nullable=True, comment='Max amount without receipt (e.g., $75 for meals)'),
    sa.Column('irs_notes', sa.Text(), nullable=True, comment='IRS guidelines for this category'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='When record was deleted (NULL is active)'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_tax_categories_company_id'), 'tax_categories', ['company_id'], unique=False)
    op.create_unique_constraint(None, 'bank_transactions', ['id'])
    op.create_unique_constraint(None, 'reconciliations', ['id'])
    op.add_column('transactions', sa.Column('tax_category_id', sa.UUID(), nullable=True, comment='Tax category'))
    op.add_column('transactions', sa.Column('is_deductible', sa.Boolean(), nullable=True, comment='Is this expense tax deductible?'))
    op.add_column('transactions', sa.Column('deductible_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment="Amount that's deductible for tax"))
    op.add_column('transactions', sa.Column('tax_year', sa.Numeric(precision=4, scale=0), nullable=True, comment='Tax year (YYYY)'))
    op.create_foreign_key(None, 'transactions', 'tax_categories', ['tax_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'tax_year')
    op.drop_column('transactions', 'deductible_amount')
    op.drop_column('transactions', 'is_deductible')
    op.drop_column('transactions', 'tax_category_id')
    op.drop_constraint(None, 'reconciliations', type_='unique')
    op.drop_constraint(None, 'bank_transactions', type_='unique')
    op.drop_index(op.f('ix_tax_categories_company_id'), table_name='tax_categories')
    op.drop_table('tax_categories')
    # ### end Alembic commands ###
