from sqlalchemy import Column, String, Date, Numeric, JSON, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship, Session
from typing import Dict, Any, List
from datetime import date
from decimal import Decimal
from app.models.base import BaseModel

class FinancialStatement(BaseModel):
    """Financial statement stores generated reports,
    each statement is a snapshot at a point in time"""

    __tablename__ = "financial_statements"

    company_id = Column(
        UUID(as_uuid=True),
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    statement_type = Column(
        String(50),
        nullable=False,
        comment="Type: income_statement, balance_sheet, cash_flow"
    )

    period_start = Column(
        Date,
        nullable=False,
        comment="Period start date"
    )

    period_end = Column(
        Date,
        nullable=False,
        index=True,
        comment="Period end date (as of date)"
    )

    data = Column(
        JSON,
        nullable=False,
        comment="Statement data (line items, totals, etc.)"
    )

    status = Column(
        String(20),
        default="draft",
        nullable=False,
        comment="Status: draft, final, published"
    )

    generated_by = Column(
        String(20),
        default="ai",
        nullable=False,
        comment="Generated by: ai, user, system"
    )

    generated_by_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=True
    )

    notes = Column(
        String,
        nullable=True,
        comment="Notes about this statement"
    )

    company = relationship("Company", backref="financial_statements")
    generated_by_user = relationship("User")

    __table_args__ = (
        Index('idx_fs_company_type_date', 'company_id', 'statement_type', 'period_end'),
    )

    @classmethod
    def create_statement(
        cls,
        db: Session,
        company_id: str,
        statement_type: str,
        period_start: date,
        period_end: date,
        data: Dict[str, Any],
        generated_by: str = "ai",
        generated_by_id: str = None
    ) -> 'FinancialStatement':
        """Create a financial statement"""

        statement = cls(
            company_id=company_id,
            statement_type=statement_type,
            period_start=period_start,
            period_end=period_end,
            data=data,
            generated_by=generated_by,
            generated_by_id=generated_by_id,
            status="draft"
        )
        statement.save(db)
        return statement

    @classmethod
    @classmethod
    def get_latest(
        cls,
        db: Session,
        company_id: str,
        statement_type: str
    ) -> 'FinancialStatement':
        """Get latest statement of a type"""

        return db.query(cls).filter(
            cls.company_id == company_id,
            cls.statement_type == statement_type,
            cls.deleted_at.is_(None)
        ).order_by(cls.period_end.desc()).first()


    def finalize(self, db: Session):
        """Mark statement as final"""
        self.status = "final"
        self.update(db)

    def publish(self, db: Session):
        """Publish statement (visible to users or auditors)"""
        self.status = "published"
        self.update(db)

    def __repr__(self) -> str:
        return f"<FinancialStatement({self.statement_type}, {self.period_end})>"


